export const mockCategories = [
    { id: 1, name: "Product", slug: "product", displayOrder: 1, status: "active" },
    { id: 2, name: "Design", slug: "design", displayOrder: 2, status: "active" },
    { id: 3, name: "Growth", slug: "growth", displayOrder: 3, status: "active" },
    { id: 4, name: "AI & ML", slug: "ai-ml", displayOrder: 4, status: "active" },
    { id: 5, name: "Cloud Computing", slug: "cloud-computing", displayOrder: 5, status: "active" },
    { id: 6, name: "Data Science", slug: "data-science", displayOrder: 6, status: "active" },
    { id: 7, name: "Cyber Security", slug: "cyber-security", displayOrder: 7, status: "active" },
    { id: 8, name: "Digital Marketing", slug: "digital-marketing", displayOrder: 8, status: "active" },
  ];
  
  export const mockPrograms = [
    {
      id: 1,
      title: "Product Management Mastery",
      slug: "product-management-mastery",
      thumbnail: null,
      banner: null,
      categoryId: 1,
      categoryName: "Product",
      instructor: "Ahmed Raza",
      instructorCompany: "Google",
      difficulty: "Intermediate",
      durationWeeks: 12,
      lessonsCount: 81,
      projectsCount: 3,
      studentsCount: 1240,
      rating: 4.8,
      price: 12999,
      offerText: "50% OFF - Limited Time",
      displayOrder: 1,
      status: "active",
      createdAt: "2026-01-15",
      shortDescription: "Master the art of product management with hands-on projects and real-world case studies.",
      aboutProgram: "<p>This comprehensive program covers everything from product strategy to execution...</p>",
      learningOutcomes: [
        { id: 1, text: "Product Strategy" },
        { id: 2, text: "Product Analytics" },
        { id: 3, text: "Market Research" },
        { id: 4, text: "Product Roadmapping" },
      ],
      highlights: [
        { id: 1, text: "81 Lessons" },
        { id: 2, text: "5 Live Sessions" },
        { id: 3, text: "3 Industry Projects" },
        { id: 4, text: "Certificate of Completion" },
      ],
      faqs: [
        { id: 1, question: "Who is this program for?", answer: "This program is designed for aspiring product managers, entrepreneurs, and business professionals looking to transition into product management." },
        { id: 2, question: "What are the prerequisites?", answer: "No prior product management experience is required. Basic understanding of business concepts is helpful." },
        { id: 3, question: "Will I receive a certificate?", answer: "Yes, upon successful completion you will receive a verified certificate of completion." },
      ],
      programBenefits: [
        { id: 1, text: "Industry-recognized certification" },
        { id: 2, text: "Mentorship from top PMs" },
        { id: 3, text: "Job placement assistance" },
      ],
      careerOpportunities: [
        { id: 1, text: "Product Manager" },
        { id: 2, text: "Associate PM" },
        { id: 3, text: "Product Analyst" },
      ],
      enrollmentButtonText: "Enroll Now",
      enrollmentUrl: "https://ilm.ora/enroll/product-management",
      syllabusButtonText: "Download Syllabus",
      syllabusType: "manual",
      syllabusFile: null,
      syllabus: [
        {
          id: 1, weekNumber: 1, title: "Introduction to Product Management",
          startDate: "2026-02-01", endDate: "2026-02-07",
          modules: [
            {
              id: 1, title: "What is Product Management?", description: "Understanding the PM role and responsibilities",
              sessions: [
                { id: 1, title: "PM Role Overview", type: "Live", date: "2026-02-02", time: "18:00", duration: 60 },
                { id: 2, title: "PM Tools & Frameworks", type: "Recorded", date: "2026-02-03", time: "", duration: 45 },
              ]
            }
          ]
        },
        {
          id: 2, weekNumber: 2, title: "Product Strategy",
          startDate: "2026-02-08", endDate: "2026-02-14",
          modules: [
            {
              id: 2, title: "Building Product Strategy", description: "Learn how to create and communicate product strategy",
              sessions: [
                { id: 3, title: "Vision & Strategy", type: "Live", date: "2026-02-09", time: "18:00", duration: 60 },
                { id: 4, title: "Strategy Assignment", type: "Assignment", date: "2026-02-12", time: "", duration: 120 },
              ]
            }
          ]
        },
      ],
    },
    {
      id: 2,
      title: "UX/UI Design Bootcamp",
      slug: "ux-ui-design-bootcamp",
      thumbnail: null,
      banner: null,
      categoryId: 2,
      categoryName: "Design",
      instructor: "Sara Khan",
      instructorCompany: "Adobe",
      difficulty: "Beginner",
      durationWeeks: 8,
      lessonsCount: 56,
      projectsCount: 5,
      studentsCount: 890,
      rating: 4.9,
      price: 9999,
      offerText: "Early Bird - 30% OFF",
      displayOrder: 2,
      status: "active",
      createdAt: "2026-01-20",
      shortDescription: "Learn UX/UI design from scratch with industry tools like Figma and Adobe XD.",
      aboutProgram: "<p>A complete design bootcamp covering user research, wireframing, prototyping...</p>",
      learningOutcomes: [],
      highlights: [],
      faqs: [],
      programBenefits: [],
      careerOpportunities: [],
      enrollmentButtonText: "Join Now",
      enrollmentUrl: "",
      syllabusButtonText: "View Syllabus",
      syllabusType: "manual",
      syllabusFile: null,
      syllabus: [],
    },
    {
      id: 3,
      title: "Data Science with Python",
      slug: "data-science-python",
      thumbnail: null,
      banner: null,
      categoryId: 6,
      categoryName: "Data Science",
      instructor: "Dr. Farrukh Ahmed",
      instructorCompany: "Microsoft",
      difficulty: "Advanced",
      durationWeeks: 16,
      lessonsCount: 120,
      projectsCount: 6,
      studentsCount: 2100,
      rating: 4.7,
      price: 19999,
      offerText: "",
      displayOrder: 3,
      status: "inactive",
      createdAt: "2026-02-01",
      shortDescription: "Deep dive into data science, machine learning, and AI with Python.",
      aboutProgram: "<p>Master Python for data science from fundamentals to advanced ML algorithms...</p>",
      learningOutcomes: [],
      highlights: [],
      faqs: [],
      programBenefits: [],
      careerOpportunities: [],
      enrollmentButtonText: "Enroll Now",
      enrollmentUrl: "",
      syllabusButtonText: "Download Syllabus",
      syllabusType: "upload",
      syllabusFile: { name: "data-science-syllabus.pdf", size: "2.4 MB", uploadDate: "2026-02-01" },
      syllabus: [],
    },
  ];